version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "conf"
      POSTGRES_USER: "conf"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"